-- File: seed_payment_methods.sql
-- Description: Seeds default payment methods for the first tenant found.
-- This script assumes the 'tenants' table has at least one entry.

SET @tenant_id = (SELECT id FROM tenants LIMIT 1);

SELECT IF(@tenant_id IS NULL,
    'Error: No tenant found in `tenants` table. Please add a tenant first or specify a tenant_id.',
    CONCAT('Tenant ID selected: ', @tenant_id)
) AS TenantSelectionStatus;

-- Seed payment_methods
-- Using INSERT IGNORE to skip insertion if a payment method with the same (tenant_id, code) already exists,
-- relying on the UNIQUE KEY `unique_tenant_payment_code` (tenant_id, code).
-- These INSERTs will only proceed if @tenant_id is not NULL.
INSERT IGNORE INTO payment_methods (id, tenant_id, name, is_active, requires_terminal, icon, sort_order, created_at, updated_at)
SELECT UUID(), @tenant_id, 'Cash', TRUE, FALSE, 'cash', 1, NOW(), NOW() WHERE @tenant_id IS NOT NULL
UNION ALL
SELECT UUID(), @tenant_id, 'Credit/Debit Card', TRUE, TRUE, 'credit-card', 2, NOW(), NOW() WHERE @tenant_id IS NOT NULL
UNION ALL
SELECT UUID(), @tenant_id, 'UPI', TRUE, TRUE, 'phone', 3, NOW(), NOW() WHERE @tenant_id IS NOT NULL
UNION ALL
-- Add the 'No Payment Required' method with a specific nil UUID
-- The 'code' column is generated by the database based on the 'name'.
SELECT '00000000-0000-0000-0000-000000000000', @tenant_id, 'No Payment Required', TRUE, FALSE, 'check-circle', 99, NOW(), NOW() WHERE @tenant_id IS NOT NULL;


-- Initialize/Update tenant_payment_settings for the same tenant
-- Uses ON DUPLICATE KEY UPDATE as tenant_id is the Primary Key for this table.
INSERT INTO tenant_payment_settings (tenant_id, default_currency, allow_partial_payments, created_at, updated_at)
SELECT @tenant_id, 'INR', TRUE, NOW(), NOW()
WHERE @tenant_id IS NOT NULL -- Ensure we only attempt if a tenant_id was found
ON DUPLICATE KEY UPDATE
    default_currency = VALUES(default_currency),
    allow_partial_payments = VALUES(allow_partial_payments),
    updated_at = NOW();

SELECT 'Payment methods and tenant payment settings seeding attempt completed.' AS Status;
